/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateCurrentUser"];
        trace?: never;
    };
    "/api/v1/me/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changeCurrentUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStudents"];
        put?: never;
        post: operations["createStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        get: operations["getStudent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateStudent"];
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}/invitation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resendUserInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/v1/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateOrganization"];
        trace?: never;
    };
    "/api/v1/students/{studentId}/access": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        get: operations["listStudentAccess"];
        put?: never;
        post: operations["setStudentAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateStudentAccess"];
        trace?: never;
    };
    "/api/v1/students/{studentId}/access/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
                userId: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeStudentAccess"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{studentId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        get: operations["listStudentDocuments"];
        put?: never;
        post: operations["uploadStudentDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentID"];
            };
            cookie?: never;
        };
        get: operations["getDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{documentId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentID"];
            };
            cookie?: never;
        };
        get: operations["listDocumentVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{documentId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentID"];
            };
            cookie?: never;
        };
        get: operations["downloadCurrentDocumentVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{documentId}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentID"];
            };
            cookie?: never;
        };
        get: operations["previewPDF"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{documentId}/versions/{versionId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentID"];
                versionId: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        get: operations["downloadDocumentVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{documentId}/editor": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentID"];
            };
            cookie?: never;
        };
        get: operations["getDocumentEditorConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{studentId}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        get: operations["listStudentNotes"];
        put?: never;
        post: operations["createStudentNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{studentId}/support-cases": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        get: operations["listStudentSupportCases"];
        put?: never;
        post: operations["createStudentSupportCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support-cases/{caseId}/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSupportGoal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support-cases/{caseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSupportCaseStatus"];
        trace?: never;
    };
    "/api/v1/support-goals/{goalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSupportGoalStatus"];
        trace?: never;
    };
    "/api/v1/support-goals/{goalId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createGoalProgress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMeetings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{studentId}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        get: operations["listStudentMeetings"];
        put?: never;
        post: operations["createStudentMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meetingId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
            };
            cookie?: never;
        };
        get: operations["getMeeting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMeeting"];
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMyTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{studentId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        get: operations["listStudentTasks"];
        put?: never;
        post: operations["createStudentTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateTaskStatus"];
        trace?: never;
    };
    "/api/v1/students/{studentId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        get: operations["getStudentTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            status: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AcceptInvitation: {
            token: string;
            /**
             * Format: password
             * @description Must contain at least one letter and one digit.
             */
            password: string;
        };
        UpdateProfile: {
            lastName: string;
            firstName: string;
            middleName?: string | null;
            /** Format: email */
            email: string;
        };
        ChangePassword: {
            /** Format: password */
            currentPassword: string;
            /**
             * Format: password
             * @description Must contain at least one letter and one digit.
             */
            newPassword: string;
        };
        CurrentUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            lastName: string;
            firstName: string;
            middleName?: string | null;
            organization: {
                /** Format: uuid */
                id: string;
                name: string;
            };
            permissions: string[];
        };
        CreateStudent: {
            lastName: string;
            firstName: string;
            middleName?: string | null;
            /** Format: date */
            birthDate?: string | null;
            className?: string | null;
        };
        Student: {
            /** Format: uuid */
            id: string;
            lastName: string;
            firstName: string;
            middleName?: string | null;
            /** Format: date */
            birthDate?: string | null;
            className?: string | null;
            /** Format: int64 */
            documentCount: number;
            specialists: string[];
            activeSupport: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Role: {
            /** Format: uuid */
            id: string;
            key: string;
            name: string;
            isSystem: boolean;
            permissions: string[];
        };
        CreateUser: {
            lastName: string;
            firstName: string;
            middleName?: string | null;
            /** Format: email */
            email: string;
            roleKey: string;
        };
        OrganizationUser: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            roleId: string;
            displayName: string;
            lastName?: string;
            firstName?: string;
            middleName?: string | null;
            /** Format: email */
            email: string;
            roleKey: string;
            roleName: string;
            /** @enum {string} */
            status: "active" | "invited" | "blocked";
            /** Format: date-time */
            createdAt: string;
            /**
             * @description Present in the create response.
             * @enum {string}
             */
            invitationDelivery?: "sent" | "failed";
            /**
             * @description Safe delivery failure class present when invitationDelivery is failed.
             * @enum {string}
             */
            invitationError?: "smtp_connection_failed" | "smtp_tls_failed" | "smtp_authentication_failed" | "smtp_sender_rejected" | "smtp_recipient_rejected" | "smtp_send_failed";
        };
        /** @enum {string} */
        StudentGrant: "view" | "upload" | "download" | "edit";
        StudentAccess: {
            /** Format: uuid */
            userId: string;
            displayName: string;
            /** Format: email */
            email: string;
            roleKey: string;
            roleName: string;
            grants: components["schemas"]["StudentGrant"][];
        };
        SetStudentAccess: {
            /** Format: uuid */
            userId: string;
            grants: components["schemas"]["StudentGrant"][];
        };
        AuditEvent: {
            /** Format: uuid */
            id: string;
            actorName: string;
            action: string;
            resourceType: string;
            /** Format: uuid */
            resourceId?: string | null;
            /** Format: date-time */
            createdAt: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        Document: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            studentId: string;
            title: string;
            documentType?: string | null;
            /** @enum {string} */
            confidentialityLevel: "standard" | "restricted";
            currentVersion: components["schemas"]["DocumentVersion"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DocumentVersion: {
            /** Format: uuid */
            id: string;
            versionNumber: number;
            originalFilename: string;
            /** @enum {string} */
            mimeType: "application/pdf" | "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
            /** Format: int64 */
            size: number;
            sha256: string;
            changedBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        Dashboard: {
            /** Format: int64 */
            studentCount: number;
            /** Format: int64 */
            upcomingMeetings: number;
            /** Format: int64 */
            tasksToday: number;
            /** Format: int64 */
            overdueTasks: number;
            attention?: components["schemas"]["DashboardItem"][] | null;
            upcoming?: components["schemas"]["DashboardItem"][] | null;
            recentStudents?: components["schemas"]["RecentStudent"][] | null;
        };
        DashboardItem: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "task" | "meeting";
            title: string;
            /** Format: uuid */
            studentId?: string | null;
            studentName?: string | null;
            /** Format: date-time */
            occurredAt: string;
        };
        RecentStudent: {
            /** Format: uuid */
            id: string;
            fullName: string;
            className?: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        StudentNote: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            studentId: string;
            /** Format: uuid */
            authorUserId: string;
            authorName: string;
            /** @enum {string} */
            type: "observation" | "meeting" | "contact" | "other";
            body: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateStudentNote: {
            /** @enum {string} */
            type: "observation" | "meeting" | "contact" | "other";
            body: string;
        };
        SupportCase: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            studentId: string;
            title: string;
            reason?: string | null;
            /** @enum {string} */
            status: "active" | "monitoring" | "completed";
            /** @enum {string} */
            priority: "low" | "normal" | "high";
            /** Format: uuid */
            responsibleUserId?: string | null;
            responsibleName?: string | null;
            /** Format: date */
            openedAt: string;
            /** Format: date */
            closedAt?: string | null;
            goals: components["schemas"]["SupportGoal"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateSupportCase: {
            title: string;
            reason?: string;
            /** @enum {string} */
            priority: "low" | "normal" | "high";
            /** Format: uuid */
            responsibleUserId?: string | null;
        };
        SupportGoal: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            supportCaseId: string;
            title: string;
            description?: string | null;
            /** Format: date */
            targetDate?: string | null;
            /** @enum {string} */
            status: "planned" | "in_progress" | "achieved" | "cancelled";
            progress: components["schemas"]["GoalProgress"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateSupportGoal: {
            title: string;
            description?: string;
            /** Format: date */
            targetDate?: string;
        };
        GoalProgress: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            goalId: string;
            authorName: string;
            body: string;
            /** @enum {string|null} */
            progressStatus?: "on_track" | "needs_attention" | "achieved" | null;
            /** Format: date */
            observedAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateGoalProgress: {
            body: string;
            /** @enum {string} */
            progressStatus?: "on_track" | "needs_attention" | "achieved";
            /** Format: date */
            observedAt?: string;
        };
        CouncilMeeting: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            studentId: string;
            studentName: string;
            /** Format: date-time */
            scheduledAt: string;
            /** @enum {string} */
            status: "planned" | "completed" | "cancelled";
            subject: string;
            questions?: string | null;
            notes?: string | null;
            decision?: string | null;
            recommendations?: string | null;
            participantIds: string[];
            participantNames: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateCouncilMeeting: {
            /** Format: date-time */
            scheduledAt: string;
            subject: string;
            questions?: string;
            notes?: string;
            participantIds?: string[];
        };
        UpdateCouncilMeeting: components["schemas"]["CreateCouncilMeeting"] & {
            /** @enum {string} */
            status: "planned" | "completed" | "cancelled";
            decision: string;
            recommendations: string;
        };
        StudentTask: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            studentId?: string | null;
            studentName?: string | null;
            /** Format: uuid */
            meetingId?: string | null;
            title: string;
            description?: string | null;
            /** Format: uuid */
            assigneeUserId: string;
            assigneeName: string;
            /** Format: date-time */
            dueAt?: string | null;
            /** @enum {string} */
            status: "todo" | "done";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateStudentTask: {
            title: string;
            description?: string;
            /** Format: uuid */
            assigneeUserId: string;
            /** Format: date-time */
            dueAt?: string;
            /** Format: uuid */
            meetingId?: string | null;
        };
        TimelineEntry: {
            /** Format: uuid */
            id: string;
            action: string;
            actorName: string;
            resourceType: string;
            /** Format: uuid */
            resourceId?: string | null;
            title?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                requestId?: string;
            };
        };
    };
    responses: {
        /** @description Healthy. */
        Health: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["HealthResponse"];
            };
        };
        /** @description Stable public error envelope. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        StudentID: string;
        DocumentID: string;
        VersionID: string;
        UserID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Health"];
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Health"];
            503: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session created. Sets opaque HttpOnly session and CSRF cookies. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and cookies cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvitation"];
            };
        };
        responses: {
            /** @description Invitation accepted and password set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
            410: components["responses"]["Error"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active session and effective permissions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    updateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfile"];
            };
        };
        responses: {
            /** @description Own profile updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    changeCurrentUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePassword"];
            };
        };
        responses: {
            /** @description Password changed and other sessions revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    listStudents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Students visible to the current membership. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Student"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudent"];
            };
        };
        responses: {
            /** @description Student created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    getStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped student. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updateStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudent"];
            };
        };
        responses: {
            /** @description Tenant-scoped student updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Roles configured for the current organization. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Role"][];
                    };
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users and active memberships in the current organization. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["OrganizationUser"][];
                    };
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUser"];
            };
        };
        responses: {
            /** @description Invited account created. Delivery status reports whether SMTP accepted the message. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationUser"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    resendUserInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Previous pending invitation revoked and a new email sent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUser"];
            };
        };
        responses: {
            /** @description Tenant-scoped user profile and role updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationUser"];
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    updateOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Current tenant organization updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
        };
    };
    listStudentAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active additive grants for the student. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["StudentAccess"][];
                    };
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    setStudentAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStudentAccess"];
            };
        };
        responses: {
            /** @description Grants replaced atomically. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updateStudentAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStudentAccess"];
            };
        };
        responses: {
            /** @description Grants replaced atomically. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
        };
    };
    revokeStudentAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
                userId: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All grants revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Append-only audit events for the current organization. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AuditEvent"][];
                    };
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listStudentDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized document workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Document"][];
                    };
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    uploadStudentDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description DOCX or PDF
                     */
                    file: string;
                    title?: string;
                    documentType?: string;
                    /**
                     * @default standard
                     * @enum {string}
                     */
                    confidentialityLevel?: "standard" | "restricted";
                };
            };
        };
        responses: {
            /** @description Scanned immutable version 1 stored in private S3. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            403: components["responses"]["Error"];
            413: components["responses"]["Error"];
            415: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped document metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listDocumentVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable version history, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["DocumentVersion"][];
                    };
                };
            };
            403: components["responses"]["Error"];
        };
    };
    downloadCurrentDocumentVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized current version stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": string;
                };
            };
            403: components["responses"]["Error"];
        };
    };
    previewPDF: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized inline PDF stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            403: components["responses"]["Error"];
            415: components["responses"]["Error"];
        };
    };
    downloadDocumentVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentID"];
                versionId: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized immutable version stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getDocumentEditorConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JWT-signed ONLYOFFICE config for the current DOCX version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        documentServerUrl: string;
                        config: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            403: components["responses"]["Error"];
            415: components["responses"]["Error"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped daily workspace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listStudentNotes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible student notes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["StudentNote"][];
                    };
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createStudentNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudentNote"];
            };
        };
        responses: {
            /** @description Note created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentNote"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listStudentSupportCases: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Student support cases with goals and progress */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["SupportCase"][];
                    };
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createStudentSupportCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSupportCase"];
            };
        };
        responses: {
            /** @description Support case created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportCase"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createSupportGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSupportGoal"];
            };
        };
        responses: {
            /** @description Goal created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportGoal"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    updateSupportCaseStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "active" | "monitoring" | "completed";
                };
            };
        };
        responses: {
            /** @description Support case status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportCase"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    updateSupportGoalStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "planned" | "in_progress" | "achieved" | "cancelled";
                };
            };
        };
        responses: {
            /** @description Support goal status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportGoal"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createGoalProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGoalProgress"];
            };
        };
        responses: {
            /** @description Progress entry created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalProgress"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listMeetings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meetings for visible students */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["CouncilMeeting"][];
                    };
                };
            };
        };
    };
    listStudentMeetings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Student meetings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["CouncilMeeting"][];
                    };
                };
            };
        };
    };
    createStudentMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCouncilMeeting"];
            };
        };
        responses: {
            /** @description Meeting created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CouncilMeeting"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    getMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped meeting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CouncilMeeting"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    updateMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meetingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCouncilMeeting"];
            };
        };
        responses: {
            /** @description Meeting updated or completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CouncilMeeting"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listMyTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tasks assigned to current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["StudentTask"][];
                    };
                };
            };
        };
    };
    listStudentTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Student tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["StudentTask"][];
                    };
                };
            };
        };
    };
    createStudentTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudentTask"];
            };
        };
        responses: {
            /** @description Task created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentTask"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    updateTaskStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "todo" | "done";
                };
            };
        };
        responses: {
            /** @description Task status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentTask"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    getStudentTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unified student activity timeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["TimelineEntry"][];
                    };
                };
            };
            403: components["responses"]["Error"];
        };
    };
}
