"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ClipboardPlus, MessageSquarePlus, Plus, Target } from "lucide-react";
import { useState } from "react";

import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { StatusBadge } from "@/components/ui/status-badge";
import { GoalDialog, ProgressDialog, SupportCaseDialog } from "@/features/casework/casework-dialogs";
import { caseworkAPI } from "@/lib/api/casework";
import { formatDate, relativeDate } from "@/lib/format";

export function StudentSupport({ studentId, canWrite }: { studentId: string; canWrite: boolean }) {
  const query = useQuery({ queryKey: ["student-cases", studentId], queryFn: () => caseworkAPI.cases(studentId) });
  const client = useQueryClient(); const [dialog, setDialog] = useState<{ type: "case" | "goal" | "progress"; id?: string } | null>(null);
  const saved = () => { setDialog(null); void client.invalidateQueries({ queryKey: ["student-cases", studentId] }); void client.invalidateQueries({ queryKey: ["student-timeline", studentId] }); void client.invalidateQueries({ queryKey: ["dashboard"] }); };
  const caseStatus = useMutation({ mutationFn: ({ id, status }: { id: string; status: "active" | "monitoring" | "completed" }) => caseworkAPI.setCaseStatus(id, status), onSuccess: saved });
  const goalStatus = useMutation({ mutationFn: ({ id, status }: { id: string; status: "planned" | "in_progress" | "achieved" | "cancelled" }) => caseworkAPI.setGoalStatus(id, status), onSuccess: saved });
  return <section className="workspace-panel support-workspace"><header className="panel-header"><div><h2>Сопровождение</h2><p>Направления работы, цели и короткая история прогресса.</p></div>{canWrite && <Button onClick={() => setDialog({ type: "case" })}><ClipboardPlus size={17} />Открыть сопровождение</Button>}</header>
    {query.isPending && <div className="page-loading"><span className="loading-spinner" />Загружаем сопровождение…</div>}{query.data?.length === 0 && <EmptyState icon={Target} title="Сопровождение ещё не открыто" description="Создайте направление работы и добавьте понятные цели." action={canWrite && <Button onClick={() => setDialog({ type: "case" })}><Plus size={17} />Открыть сопровождение</Button>} />}
    <div className="support-case-list">{query.data?.map((item) => <article className="support-case-card" key={item.id}><header><div><span className="panel-kicker">Открыто {formatDate(item.openedAt)}</span><h3>{item.title}</h3>{item.reason && <p>{item.reason}</p>}</div>{canWrite ? <label className="compact-status-field"><span className="sr-only">Статус сопровождения</span><select aria-label={`Статус сопровождения ${item.title}`} value={item.status} disabled={caseStatus.isPending} onChange={(event) => caseStatus.mutate({ id: item.id, status: event.target.value as "active" | "monitoring" | "completed" })}><option value="active">Активно</option><option value="monitoring">Мониторинг</option><option value="completed">Завершено</option></select></label> : <StatusBadge tone={item.priority === "high" ? "warning" : item.status === "completed" ? "neutral" : "success"}>{item.status === "monitoring" ? "Мониторинг" : item.status === "completed" ? "Завершено" : "Активно"}</StatusBadge>}</header><div className="goal-list">{item.goals.map((goal) => <section key={goal.id}><header><span className="goal-marker"><Target size={16} /></span><div><strong>{goal.title}</strong><small>{goal.targetDate ? `Контроль: ${formatDate(goal.targetDate)}` : "Без контрольной даты"}</small></div>{canWrite ? <label className="compact-status-field"><span className="sr-only">Статус цели</span><select aria-label={`Статус цели ${goal.title}`} value={goal.status} disabled={goalStatus.isPending} onChange={(event) => goalStatus.mutate({ id: goal.id, status: event.target.value as "planned" | "in_progress" | "achieved" | "cancelled" })}><option value="planned">Запланирована</option><option value="in_progress">В работе</option><option value="achieved">Достигнута</option><option value="cancelled">Отменена</option></select></label> : <StatusBadge tone={goal.status === "achieved" ? "success" : "info"}>{goal.status === "achieved" ? "Достигнута" : goal.status === "in_progress" ? "В работе" : goal.status === "cancelled" ? "Отменена" : "Запланирована"}</StatusBadge>}</header>{goal.description && <p>{goal.description}</p>}{goal.progress[0] && <div className="latest-progress"><MessageSquarePlus size={15} /><span><strong>Последнее наблюдение · {relativeDate(goal.progress[0].createdAt)}</strong><p>{goal.progress[0].body}</p></span></div>}{canWrite && <Button size="sm" variant="ghost" onClick={() => setDialog({ type: "progress", id: goal.id })}><MessageSquarePlus size={15} />Добавить наблюдение</Button>}</section>)}{item.goals.length === 0 && <p className="muted-copy">Цели пока не добавлены.</p>}</div>{canWrite && <Button size="sm" variant="outline" onClick={() => setDialog({ type: "goal", id: item.id })}><Plus size={15} />Добавить цель</Button>}</article>)}</div>
    {dialog?.type === "case" && <SupportCaseDialog studentId={studentId} onClose={() => setDialog(null)} onSaved={saved} />}{dialog?.type === "goal" && dialog.id && <GoalDialog studentId={dialog.id} onClose={() => setDialog(null)} onSaved={saved} />}{dialog?.type === "progress" && dialog.id && <ProgressDialog studentId={dialog.id} onClose={() => setDialog(null)} onSaved={saved} />}
  </section>;
}
